### ISSUE TITLE
Add new useful tiling layouts

### ISSUE THREAD

**Issue by devheadtech** [devheadtech/fadwm#6]
### Summary
Add new useful tiling layout

### Tasks
- [x] Review for useful patches from upstream
- [x] Integrate Tile left
- [x] Integrate Tile right
- [x] Integrate Stack top
- [x] Integrate Stack bottom
- [x] Integrate Center Master
- [x] Integrate Center float
- [x] Integrate Fibonacci spiral
- [x] Integrate Fibonacci dwindle
